// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: market_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for getting market data
type GetMarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // List of symbols to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDataRequest) Reset() {
	*x = GetMarketDataRequest{}
	mi := &file_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataRequest) ProtoMessage() {}

func (x *GetMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataRequest.ProtoReflect.Descriptor instead.
func (*GetMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetMarketDataRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// Response message containing market data
type GetMarketDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketData    []*MarketData          `protobuf:"bytes,1,rep,name=market_data,json=marketData,proto3" json:"market_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketDataResponse) Reset() {
	*x = GetMarketDataResponse{}
	mi := &file_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketDataResponse) ProtoMessage() {}

func (x *GetMarketDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketDataResponse.ProtoReflect.Descriptor instead.
func (*GetMarketDataResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetMarketDataResponse) GetMarketData() []*MarketData {
	if x != nil {
		return x.MarketData
	}
	return nil
}

// Individual market data item
type MarketData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastQuote     float32                `protobuf:"fixed32,3,opt,name=last_quote,json=lastQuote,proto3" json:"last_quote,omitempty"`
	Category      int32                  `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketData) Reset() {
	*x = MarketData{}
	mi := &file_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketData) ProtoMessage() {}

func (x *MarketData) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketData.ProtoReflect.Descriptor instead.
func (*MarketData) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *MarketData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketData) GetLastQuote() float32 {
	if x != nil {
		return x.LastQuote
	}
	return 0
}

func (x *MarketData) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

// Request for streaming market data
type StreamMarketDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMarketDataRequest) Reset() {
	*x = StreamMarketDataRequest{}
	mi := &file_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMarketDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMarketDataRequest) ProtoMessage() {}

func (x *StreamMarketDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMarketDataRequest.ProtoReflect.Descriptor instead.
func (*StreamMarketDataRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMarketDataRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

// Streaming market data update
type MarketDataUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *MarketData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataUpdate) Reset() {
	*x = MarketDataUpdate{}
	mi := &file_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataUpdate) ProtoMessage() {}

func (x *MarketDataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataUpdate.ProtoReflect.Descriptor instead.
func (*MarketDataUpdate) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *MarketDataUpdate) GetData() *MarketData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MarketDataUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_market_data_proto protoreflect.FileDescriptor

const file_market_data_proto_rawDesc = "" +
	"\n" +
	"\x11market_data.proto\x12\vmarket_data\"0\n" +
	"\x14GetMarketDataRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"Q\n" +
	"\x15GetMarketDataResponse\x128\n" +
	"\vmarket_data\x18\x01 \x03(\v2\x17.market_data.MarketDataR\n" +
	"marketData\"s\n" +
	"\n" +
	"MarketData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"last_quote\x18\x03 \x01(\x02R\tlastQuote\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\x05R\bcategory\"3\n" +
	"\x17StreamMarketDataRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"]\n" +
	"\x10MarketDataUpdate\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.market_data.MarketDataR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xc6\x01\n" +
	"\x11MarketDataService\x12V\n" +
	"\rGetMarketData\x12!.market_data.GetMarketDataRequest\x1a\".market_data.GetMarketDataResponse\x12Y\n" +
	"\x10StreamMarketData\x12$.market_data.StreamMarketDataRequest\x1a\x1d.market_data.MarketDataUpdate0\x01B\tZ\a./protob\x06proto3"

var (
	file_market_data_proto_rawDescOnce sync.Once
	file_market_data_proto_rawDescData []byte
)

func file_market_data_proto_rawDescGZIP() []byte {
	file_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)))
	})
	return file_market_data_proto_rawDescData
}

var file_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_market_data_proto_goTypes = []any{
	(*GetMarketDataRequest)(nil),    // 0: market_data.GetMarketDataRequest
	(*GetMarketDataResponse)(nil),   // 1: market_data.GetMarketDataResponse
	(*MarketData)(nil),              // 2: market_data.MarketData
	(*StreamMarketDataRequest)(nil), // 3: market_data.StreamMarketDataRequest
	(*MarketDataUpdate)(nil),        // 4: market_data.MarketDataUpdate
}
var file_market_data_proto_depIdxs = []int32{
	2, // 0: market_data.GetMarketDataResponse.market_data:type_name -> market_data.MarketData
	2, // 1: market_data.MarketDataUpdate.data:type_name -> market_data.MarketData
	0, // 2: market_data.MarketDataService.GetMarketData:input_type -> market_data.GetMarketDataRequest
	3, // 3: market_data.MarketDataService.StreamMarketData:input_type -> market_data.StreamMarketDataRequest
	1, // 4: market_data.MarketDataService.GetMarketData:output_type -> market_data.GetMarketDataResponse
	4, // 5: market_data.MarketDataService.StreamMarketData:output_type -> market_data.MarketDataUpdate
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_data_proto_init() }
func file_market_data_proto_init() {
	if File_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_proto_depIdxs,
		MessageInfos:      file_market_data_proto_msgTypes,
	}.Build()
	File_market_data_proto = out.File
	file_market_data_proto_goTypes = nil
	file_market_data_proto_depIdxs = nil
}
